"""add road network version table

Revision ID: 00df7b8f5ec9
Revises: 40ec61cebebd
Create Date: 2025-09-06 08:40:21.598412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00df7b8f5ec9'
down_revision: Union[str, Sequence[str], None] = '40ec61cebebd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_network_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['network_id'], ['road_networks.id'], name='fk_versions_network_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('road_network_versions')
    # ### end Alembic commands ###
