"""add road edge table

Revision ID: f1d43d189694
Revises: ac482ab357bb
Create Date: 2025-09-06 09:53:20.685122

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa

from app.adapters.models.helpers.jsonb_decimal import JSONBWithDecimal

# revision identifiers, used by Alembic.
revision: str = 'f1d43d189694'
down_revision: Union[str, Sequence[str], None] = 'ac482ab357bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('start_node_id', sa.Integer(), nullable=False),
    sa.Column('end_node_id', sa.Integer(), nullable=False),
    sa.Column('properties', JSONBWithDecimal(astext_type=sa.Text()), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='LINESTRING', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['end_node_id'], ['road_nodes.id'], name='fk_road_edges_end_node_id'),
    sa.ForeignKeyConstraint(['start_node_id'], ['road_nodes.id'], name='fk_road_edges_start_node_id'),
    sa.ForeignKeyConstraint(['version_id'], ['road_network_versions.id'], name='fk_road_edges_version_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_fast_road_edges_geometry', 'road_edges', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fast_road_edges_geometry', table_name='road_edges', postgresql_using='gist')
    op.drop_table('road_edges')
    # ### end Alembic commands ###
