"""add road node table

Revision ID: ac482ab357bb
Revises: 00df7b8f5ec9
Create Date: 2025-09-06 09:20:16.520712

"""
from typing import Sequence, Union

import geoalchemy2
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac482ab357bb'
down_revision: Union[str, Sequence[str], None] = '00df7b8f5ec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('road_nodes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('network_id', sa.Integer(), nullable=False),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.ForeignKeyConstraint(['network_id'], ['road_networks.id'], name='fk_road_nodes_network_id', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('network_id', 'geometry', name='uq_road_nodes_network_geometry')
    )
    op.create_index('idx_fast_road_nodes_geometry', 'road_nodes', ['geometry'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fast_road_nodes_geometry', table_name='road_nodes', postgresql_using='gist')
    op.drop_table('road_nodes')
    # ### end Alembic commands ###
